# Generated by Django 3.2.3 on 2021-06-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
                ('data_registro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_postagem', models.DateTimeField()),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.CharField(max_length=1000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.autor')),
            ],
        ),
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=750)),
                ('usuario', models.CharField(max_length=100)),
                ('data_comentario', models.DateTimeField()),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postagem')),
            ],
        ),
    ]
