# Generated by Django 3.2.3 on 2021-06-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='conteudo',
            field=models.TextField(),
        ),
    ]
