# Generated by Django 3.2.3 on 2021-06-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210622_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['data_comentario']},
        ),
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['data_postagem']},
        ),
    ]
