# Generated by Django 3.2.6 on 2021-08-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comentario_data_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
